---
name: Marty
description: A React.js/Flux Framework
url: http://martyjs.org
baseurl: /
permalink: "/blog/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num/"
relative_permalinks: true
paginate: 5
timezone: America/Los_Angeles
highlighter: rouge
defaults:
- scope:
    path: ''
    type: page
  values:
    layout: post
- scope:
    path: docs
    type: page
  values:
    layout: docs
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
sass:
  style: :compressed
  sass_dir: _css
collections:
  guides:
    title: Guides
    output: true
  api:
    title: API
    output: true
  support:
    title: Support
    output: true
  devtools:
    title: Developer Tools
    output: true
current_version: 0.11.0